# -*- coding: utf-8 -*-
"""
Created on Tue Nov 30 11:41:17 2010
This script will read a matlab mat file generated by our stage and plot the 
limit surface. The user will be prompted with a file selection GUI to select the 
mat file.
@author: Noe
"""

from scipy.io import loadmat
from matPlotTools import *

import Tkinter				#import dialog box stuff
from tkFileDialog import askopenfilename

# initialize GUI dialog box
root = Tkinter.Tk()	# initiliases the window system
root.withdraw()
# This portion asks the user for a file to parse
files = askopenfilename(filetypes=[('Matlab Mat File','*.mat')],
                       title='Select data file to process',
                       parent = root,
                       multiple = True)
root.destroy()	# window cleanup

if files:
    for file in files:
        data = loadmat(file)
        plotLS_all(data,True)
else:
    print 'No file provided'